name: Python Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask

    - name: Run the app
      run: |
        python app.py &
        echo "Start Sleep" 
        sleep 15  # Give the server time to start
        echo "End Sleep"

    - name: Test the app
      run: |
        curl --fail http://localhost:5000/ | grep "Welcome to the API"
        curl --fail http://localhost:5000/about | grep "Yagmur Ozden"
